### ISSUE TITLE
Change theme in highlight code

### ISSUE THREAD

**Issue by sophiekovalevsky** [brocaar/chirpstack-hugo-theme#1]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-hugo-theme/issues) of this repository and believe that this is not a duplicate.

## Summary
In the official website www.chirpstack.io there are several sections that contain code blocks. The main idea is to visually increase the highlight of these code blocks by adding another theme.

## What is the use-case?
It happens to myself that sometimes when I need to grab  code from www.chirpstack.io, I am not able to visualize entirerly where the code ends. I can propose to change the background color that we have and use another background color that can keep be clearly different from the main background content. 

## Implementation description
We will go from this:

![image](https://user-images.githubusercontent.com/1287883/83362392-3d158180-a367-11ea-82d4-86afeca39ca2.png)

To this:

![image](https://user-images.githubusercontent.com/1287883/83362398-51597e80-a367-11ea-81ed-651ab54d1160.png)

## Can you implement this by yourself and make a pull request?
Yes, I can.

**Comment by brocaar** [comment]
Looks great :+1:
